name: Update Server Status

on:
  schedule:
    - cron: '*/30 * * * *'  # 毎30分ごとに実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: CPU使用率の取得とJSON作成
        run: |
          mkdir -p status
          CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}')
          echo '{
            "Rack 1": [{"name": "Server A", "cpu": "'$CPU'%", "status": "ON"}],
            "Rack 2": [],
            "Rack 3": [],
            "Rack 4": []
          }' > status/status.json

      - name: Git 設定とPush
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add status/status.json
          git commit -m "Update status.json" || echo "No changes to commit"
          git push origin HEAD
