name: Update Server Status

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: CPU使用率を取得してJSON化
        run: |
          mkdir -p status
          CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
          echo '{
            "Rack 1": [{"name": "Server A", "cpu": "'$CPU'%", "status": "ON"}],
            "Rack 2": [],
            "Rack 3": [],
            "Rack 4": []
          }' > status/status.json

      - name: コミット & プッシュ
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add status/status.json
          git diff --cached --quiet && echo "No changes" || git commit -m "Update status.json"
          git push
